### ISSUE TITLE
not synced fossil mirror

### ISSUE THREAD

**Issue by barak** [venks1/emacs-fossil#2]
I note that this repo has not had commits synced back into
https://chiselapp.com/user/venks/repository/emacs-fossil
which doesn't bother me personally, but seems a bit of an indictment under these particular circumstances.

**Comment by venks1** [comment]
Hi Barak,

Can I give you write perms to the github repository?

-Venkat

**Comment by barak** [comment]
Um, sure.

**Comment by venks1** [comment]
This is now back to being sync'ed to the new improved upstream version.  Closing.
