### ISSUE TITLE
debianization

### ISSUE THREAD

**Issue by barak** [venks1/emacs-fossil#3]
I've cobbled together some debian packaging scripts for this, on the `debian` branch of my fork of this repo. Unless you object, or someone else is in the process of doing this, I'll upload it to Debian in a couple days.

One issue was version number. I just made up a version number, based on the date of the last commit. But if you'd rather have official versioned snapshots, with tags like v1.2 or whatever, that would be great; just let me know.

**Comment by barak** [comment]
On https://melpa.org/#/vc-fossil the version is shown as `20180214.1822`, should I be using that?

**Comment by venks1** [comment]
Autogenerated version numbers are fine.  The melpa one is just the timestamp of when it was fetched.

**Comment by barak** [comment]
Uploaded to Debian.
